sudo: false
language: node_js
node_js:
  - 6

before_install:
  - rvm install 2.3.3
install:
  - npm install -d
  - bundle install

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

cache:
  bundler: true
  directories:
    - node_modules

script: script/test

deploy:
  - skip_cleanup: true
  on:
    branch: master
    provider: script
    script: bundle exec jekyll build && deploy-to-gh-pages --update _site
