sudo: false
language: node_js
node_js:
  - 6
addons:
  apt:
    packages:
      - libssl1.0.0

before_install:
  - rvm install 2.3.3
  - rvm --default use 2.3.3
install:
  - npm install -d
  - bundle install

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

cache:
  bundler: true
  directories:
    - node_modules

branches:
  except:
    - gh-pages

script: script/test

deploy:
  - skip_cleanup: true
    on:
      branch: master
    provider: script
    script: rvm 2.3.3 do bundle exec jekyll build && npm install -d shelljs deploy-to-gh-pages && deploy-to-gh-pages --update _site
